[package]
name = "keylx"
version = "0.1.0"
authors = ["Andrea Tomasi <tomasiandrea.at@gmail.com>"]
edition = "2018"

[dependencies]
keyllib = { path="../keyllib"}
serde = "1.0.92"
serde_json = "1.0.39"
