[package]
name = "keylx"
version = "0.1.0"
authors = ["Andrea Tomasi <tomasiandrea.at@gmail.com>"]
edition = "2018"

[dependencies]
keyllib = { path="../keyllib"}
clap = {version="2.33.0", default-features=false}

