[package]
name = "keylx"
version = "0.1.0"
authors = ["Andrea Tomasi <tomasiandrea.at@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11 = { version = "2.18.1", features = ["xlib", "xinput"] }
